# -*- coding: utf-8 -*-
"""handle_missingValue_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1New90L5gXtoIC5mdrofG1l17kZ1er0f3
"""

import pandas as pd

data = {
    "Name" : ["Ravi","Jay","Kapil","Om","Preet"],
    "Age" : [None,25,22,None,21],
    "Salary" : [48000, 51000, None, 45000, None]
}

df = pd.DataFrame(data)
print("Original DataFrame")
print(df)



#How to find Missing value raw/column

print()
print(df.isnull().sum())



#How to find Perfect Raw/Column

print()
print(df.dropna())




#How to fill NaN value

print()
df["Age"].fillna(df["Age"].mean(), inplace=True)
df["Salary"].fillna(df["Salary"].mean(), inplace=True)
print("Perfect DataFrame")
print(df)